### ISSUE TITLE
explain ex02 solution

### ISSUE THREAD

**Issue by 0xw4n** [rydzze/CTF_Write-up#3]
can you explain in depth how did you reverse the equation?

**Comment by rydzze** [comment]
Hello 0xw4n, sorry for not giving you the full explanation.

The process is quite straightforward so let's start from the bottom.

(forgot to add ... btw the `mask` variable acts as a bitmask to obtain only 32 bits from the result.)

starting with `CMP EAX, 467BB09B` it's gonna **compare** our **obfuscated input** with **0x467BB09B** and if it's equal, then our input is correct so let's use 0x467BB09B as our input here to unravel it until we get the actual input.

`XOR EAX, BA14C823` will XOR our input in EAX register with 0xBA14C823 to get 0x467BB09B, so just **XOR** **0x467BB09B** with **0xBA14C823** and you will get **0xFC6F78B8**.

`ROL EAX, 5` will take the **first 5 bits of the left side** in the EAX register and **put it at the back** (right side). You may refer to this [link](https://www.geeksforgeeks.org/rotate-bits-of-an-integer/) for a better explanation. Simply reverse the process by taking 5 bits from the back and putting it in front (`ROR EAX, 5`).

`ADD EAX, D1507BA` will **add** the value of **0xD1507BA** to the EAX register so just subtract it. I created a **function for the subtraction process** because there are chances we get the **negative value if EAX < 0xD1507BA**. Take note that **EAX** is a **32-bit accumulator register** so it only gonna take the **32 least significant bits** and **carry out** will be **ignored** as it cannot store more than 32 bits (**Computer Architecture 101**).

`XOR EAX, AAFBBCBE`... simply **XOR** **our result** from above **with 0xAAFBBCBE** to get the original EAX content.

`ADD EAX, 0x45370DF7` ... **subtract** it just like the previous.

You may calculate it one by one like I did or you can use [Z3 Theorem Prover](https://github.com/Z3Prover/z3) w/ Python to solve it automatically just like what I did for `ex04`. 

_Hope that answers your inquiry, if there are any issues just hit me up :D_
